const FLOW_URL='https://labs.google/fx/tools/flow';
let queue=[],running=false,marketTabId=null,flowTabId=null,currentProduct=null;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const sendMarket=async payload=>{if(marketTabId===null)return;try{await chrome.tabs.sendMessage(marketTabId,{source:'marketpreco-flow-extension',...payload});}catch{}};
const sanitize=v=>String(v||'produto').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'_').replace(/^_+|_+$/g,'').slice(0,100)||'produto';
async function ensureFlowTab(){if(flowTabId!==null){try{const t=await chrome.tabs.get(flowTabId);if(t?.id)return t.id;}catch{}}const t=await chrome.tabs.create({url:FLOW_URL,active:true});flowTabId=t.id;return t.id;}
async function waitForFlow(tabId){const start=Date.now();while(Date.now()-start<45000){try{const r=await chrome.tabs.sendMessage(tabId,{type:'FLOW_PING',source:'marketpreco-flow-extension'});if(r?.ready)return true;}catch{}await sleep(500);}throw new Error('Google Flow não respondeu. Abra o Flow no Chrome e confirme a conta Google AI Pro.');}
async function fetchImage(url){if(!/^https?:\/\//i.test(String(url||'')))throw new Error('Imagem sem URL HTTPS válida.');const r=await fetch(url,{credentials:'omit',redirect:'follow'});if(!r.ok)throw new Error('Não foi possível baixar a imagem (HTTP '+r.status+').');const type=(r.headers.get('content-type')||'').split(';')[0].toLowerCase();if(!/^image\/(jpeg|png|webp)$/i.test(type))throw new Error('Imagem não é JPG, PNG ou WebP.');const b=await r.arrayBuffer();if(!b.byteLength)throw new Error('Imagem vazia.');if(b.byteLength>12*1024*1024)throw new Error('Imagem maior que 12 MB.');return {buffer:b,mimeType:type};}
async function runQueue(){if(running)return;running=true;try{const tabId=await ensureFlowTab();await waitForFlow(tabId);while(queue.length){const job=queue.shift();currentProduct=job;await sendMarket({status:'running',productId:job.id,productName:job.name,message:'Enviando a imagem para o Google Flow…'});try{const image=await fetchImage(job.image);await chrome.tabs.update(tabId,{active:true});const result=await chrome.tabs.sendMessage(tabId,{source:'marketpreco-flow-extension',type:'FLOW_GENERATE_PRODUCT',product:{id:job.id,name:job.name,imageName:sanitize(job.name)+'.jpg',prompt:job.prompt,imageBytes:image.buffer,mimeType:image.mimeType}});if(!result?.ok)throw new Error(result?.error||'O Google Flow não confirmou a geração.');await sendMarket({status:'completed',productId:job.id,productName:job.name,message:'Vídeo gerado e enviado para os downloads do Chrome.'});}catch(error){await sendMarket({status:'error',productId:job.id,productName:job.name,message:error?.message||String(error)});}currentProduct=null;await sleep(1200);}}finally{running=false;await sendMarket({status:'idle',message:'Fila do Google Flow finalizada.'});}}
chrome.runtime.onMessage.addListener((message,sender,sendResponse)=>{if(message?.source!=='marketpreco-app'||message.type!=='MARKETPRECO_FLOW_BATCH')return;if(!sender.tab?.id||!String(sender.tab.url||'').startsWith('https://pesquisaproduto.pages.dev/')){sendResponse({status:'error',message:'Solicitação não veio do MARKETPREÇO oficial.'});return;}marketTabId=sender.tab.id;const products=Array.isArray(message.products)?message.products:[];const valid=products.filter(p=>p&&p.id&&p.name&&/^https?:\/\//i.test(String(p.image||'')));if(!valid.length){sendResponse({status:'error',message:'Nenhum produto válido com imagem foi selecionado.'});return;}queue.push(...valid.map(p=>({id:String(p.id),name:String(p.name),image:String(p.image),prompt:String(p.prompt||'')})));sendResponse({status:'queued',count:valid.length,message:valid.length+' produto(s) colocado(s) na fila do Google Flow.'});runQueue().catch(error=>sendMarket({status:'error',message:error?.message||String(error)}));return true;});
chrome.tabs.onRemoved.addListener(tabId=>{if(tabId===flowTabId)flowTabId=null;if(tabId===marketTabId)marketTabId=null;});
chrome.downloads.onDeterminingFilename.addListener((item,suggest)=>{if(!currentProduct){suggest();return;}const original=String(item.filename||'video.mp4');const ext=(original.match(/\.[a-z0-9]{2,5}$/i)||['.mp4'])[0].toLowerCase();suggest({filename:'MARKETPRECO/Google-Flow/'+sanitize(currentProduct.name)+ext,conflictAction:'uniquify'});return true;});